name: Test
on: [push, pull_request]
jobs:
  test:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: python -m pip install tox
      - name: Run tests
        run: python -m tox -e $(tox --listenvs | grep py$(echo ${{ matrix.python }} | tr -d .) | tr '\n' ',')
